Pelagicore/gdbus-codegen-glibmm

codegen_glibmm/codegen.py
This avoid naming conflicts in case the project has declared a namespace
(or even a class) having the same name as the generated *Common class.
Signed-off-by: Alberto Mardegan <amardegan@luxoft.com>
=> Wrap *Common classes into an unnamed namespace

codegen_glibmm/codegen.py
The *MessageHelper classes uses corresponding *Common class, and if
there is a class or namespace with the same name as the *Common class
*MessageHelper will pick up the right thing if it is in the same
unnamed namespace.
Signed-off-by: Erik Botö <erik.boto@pelagicore.com>
=> Wrap *MessageHelper into same namespace as *Common

.travis.yml, codegen_glibmm/codegen.py, codegen_glibmm/dbustypes.py, test/common/many-types.xml, test/proxy/testproxymain.cpp, test/stub/teststubmain.cpp, test/stub/teststubmain.h
Refactor the dbus type handling code to use a hierarchical class structure instead of a lot of "if"s.
Add support for D-Bus dictionaries and structures. I made sure that the code generated for other D-Bus types wouldn't change, so that existing apps won't break.
=> Add support for more complex types

codegen_glibmm/codegen.py, gdbus-codegen-glibmm.py
- Make sure print statements has paranthesis
- Use chr() to convert int into char when calling write() with raw chars
=> Convert into python3

setup.py
By default it is using older python version.
So upgrading it to use v3.
Signed-off-by: Sapan Das <SKumarDas@luxoft.com>
=> Upgrade: Upgrade python to v3

codegen_glibmm/__init__.py, codegen_glibmm/codegen_main.py, setup.py
With this commit, we also move to specifying the version of the code
generator in codegen_glibmm/__init__.py rather than setup.py. This makes
it easier for both the code generator itself and the setup code to know
of the version.
=> codegen: Add --version

codegen_glibmm/templates/proxy.h.templ, codegen_glibmm/templates/stub.cpp.templ, tests/integration/common/many-types.xml, tests/integration/proxy/testproxymain.cpp, tests/integration/stub/teststubmain.cpp, tests/integration/stub/teststubmain.h
Methods accepting more than one parameter, where at least one of them is
a variant, were not generated correctly. This commit fixes that, and
adds a regression test.
Fixes: #28
=> codegen: fix handling of methods with variant parameters

codegen_glibmm/dbustypes.py, codegen_glibmm/parser.py, codegen_glibmm/templates/proxy.cpp.templ, tests/data/many-types/input.xml, tests/data/many-types/input_proxy.cpp, tests/data/many-types/input_stub.cpp
The previous implementation was not working at all: no documentation was
ever appearing on the generated code, as it was not in the templates.
With this commit we allow documenting methods and signals.
=> codegen: simplify handling of comments

codegen_glibmm/__init__.py, setup.py
In order to allow coinstallation with the 1.x versions, we need to
rename the installed script file and ensure that the installed python
module gets installed in its own directory. We achieve the latter by
changing the version number, since this affects the location where the
module files are installed.
=> setup.py: Rename the binary to gdbus-codegen-glibmm2

codegen_glibmm/templates/common.cpp.templ, tests/data/error_namespace/input_common.cpp, tests/data/simple/input_common.cpp
Fixes https://github.com/Pelagicore/gdbus-codegen-glibmm/issues/44
=> templates: don't leak GError when throwing exceptions

codegen_glibmm/templates/proxy.h.templ, tests/data/many-types/input_proxy.h, tests/data/simple/input_proxy.h
=> templates: Mark the proxy object as protected

codegen_glibmm/templates/common.h.templ
All ...MessageHelper were created without private section. 
In addition they were not closed by the last '}' so class definition was incomplete.
=> templates: Fix generator for ...MessageHelper classes

codegen_glibmm/templates/proxy.cpp.templ, codegen_glibmm/templates/proxy.h.templ, tests/data/many-types/input_proxy.cpp, tests/data/many-types/input_proxy.h, tests/data/simple/input_proxy.cpp, tests/data/simple/input_proxy.h
Needed because some services do not return until a potentially very long operation has finished (e.g. waiting for input from user or configuring some hardware on the system).
Default to -1 which means use the GDBusProxy default (there is a property that is also set to -1 by  efault and means "use hard coded value of 25s in GDBusConnection").
=> templates: Add timeout argument to proxy D-Bus method calls

codegen_glibmm/__init__.py, setup.py
In order to allow coinstallation with the older versions, we need to
rename the installed script file and ensure that the installed python
module gets installed in its own directory. We achieve the latter by
changing the version number, since this affects the location where the
module files are installed.
=> setup.py: Rename the binary to gdbus-codegen-glibmm3

README.md
Add a small mention that the code generates cpp code. The aim is to meet expectation of  https://github.com/Pelagicore/gdbus-codegen-glibmm/issues/3
=> README: Add clarification to description about generated code

README.md, codegen_glibmm/codegen.py, codegen_glibmm/dbustypes.py, codegen_glibmm/templates/common.h.templ, codegen_glibmm/templates/proxy.cpp.templ, codegen_glibmm/templates/proxy.h.templ, codegen_glibmm/templates/stub.cpp.templ, tests/data/many-types/input.xml, tests/data/many-types/input_common.h, tests/data/many-types/input_proxy.cpp, tests/data/many-types/input_proxy.h, tests/data/many-types/input_stub.cpp, tests/data/many-types/input_stub.h, tests/data/simple/input_proxy.cpp, tests/data/simple/input_proxy.h, tests/integration/proxy/testproxymain.cpp, tests/integration/stub/teststubmain.cpp
Makes it much easier to write e.g. a cli tool where it does not matter if one blocks. See #65 for an example where three properties needs to be set.
=> Add synchronous versions of proxy creation, property set methods and method calls

codegen_glibmm/templates/proxy.cpp.templ, codegen_glibmm/templates/proxy.h.templ, codegen_glibmm/templates/stub.cpp.templ, codegen_glibmm/templates/stub.h.templ, tests/data/many-types/input_proxy.cpp, tests/data/many-types/input_proxy.h, tests/data/many-types/input_stub.cpp, tests/data/many-types/input_stub.h, tests/data/simple/input_proxy.cpp, tests/data/simple/input_proxy.h, tests/data/simple/input_stub.cpp, tests/data/simple/input_stub.h, tests/integration/stub/teststubmain.cpp, tests/integration/stub/teststubmain.h
To avoid unnecessary reference counting. MethodInvocation has a Glib::RefPtr member, so pass that as a reference as well.
Fixes #58.
=> templates: Use references when passing around Glib::RefPtr

README.md, codegen_glibmm/dbustypes.py, codegen_glibmm/templates/proxy.cpp.templ, codegen_glibmm/templates/proxy.h.templ, codegen_glibmm/templates/stub.cpp.templ, codegen_glibmm/templates/stub.h.templ, tests/data/many-types/input_proxy.cpp, tests/data/many-types/input_proxy.h, tests/data/many-types/input_stub.cpp, tests/data/many-types/input_stub.h, tests/data/simple/input_proxy.cpp, tests/data/simple/input_proxy.h, tests/data/simple/input_stub.cpp, tests/data/simple/input_stub.h, tests/integration/proxy/testproxymain.cpp, tests/integration/proxy/testproxymain.h, tests/integration/stub/teststubmain.h
Avoids name clashes between namespace names and class names when an interface is a put "below" another one. E.g. the interfaces a.B and a.B.C would add a class named B for a.B and a namespace called B for a.B.C.
Since the proxy and stub classes are named differently now it is also OK to include *_proxy.h and *_stub.h in the same compilation unit. The use case for this would be e.g. a service with name a.B requiring a client to implement an interface with the name a.B.C .
Fixes #57 .
~~There are conflicts with #68 and #73 . Please hold with merging this until those have gone in.~~
=> Add Proxy suffix to proxies and Stub suffix to stubs

codegen_glibmm/templates/proxy.cpp.templ, tests/data/many-types/input_proxy.cpp
The *_set_finish() function in proxy template file was not calling
the proxy->call_finish() to finish the set property operation started
by proxy->call() in *_set() function. This commit adds call to
proxy->call_finish() in *_set_finish(). Also updates unittest.
Signed-off-by: Tariq Ansari <tansari@luxoft.com>
=> proxy.cpp.templ: call proxy's call_finish() in *_set_finish()

codegen_glibmm/templates/stub.cpp.templ, codegen_glibmm/templates/stub.h.templ, tests/data/many-types/input_stub.cpp, tests/data/many-types/input_stub.h, tests/data/simple/input_stub.cpp, tests/data/simple/input_stub.h
Started out by simplifying some code in a service by adding a `bool registered_object() const` method to stub instead of storing state separately and mentioning object path in error messages (instead of logging it at call site on failure). Did some other minor fixes and cleanups as well that I happened to see when looking at `register_object()`. See commit log for details.
Originally split the "Improve logging" commit into multiple ones but decided to merge them. Can break them up again if wanted.
=> Minor register object improvments and add registered_object() method

codegen_glibmm/templates/stub.cpp.templ, codegen_glibmm/templates/stub.h.templ, tests/data/many-types/input_stub.cpp, tests/data/many-types/input_stub.h, tests/data/simple/input_stub.cpp, tests/data/simple/input_stub.h
(This is a WIP, as new tests for this feature are missing, and old tests are failing; I'll fix this once the code has been reviewed, to avoid updating the templates every time :-) )
Stubs can be registered on multiple connections, and also multiple times
on the same connection, as long as object paths are different. This
commit enables this, by turning the object registration data into an
array.
Note that signals need to be emitted on each connection/path.
A check to avoid duplicate registrations (with the same connection/path)
is not needed, as it's already performed by
g_dbus_connection_register_object().
Fixes: #81
Signed-off-by: Alberto Mardegan <amardegan@luxoft.com>
=> stub: Allow registering the same instance on multiple connections/paths

codegen_glibmm/templates/proxy.cpp.templ, codegen_glibmm/templates/stub.cpp.templ, tests/data/many-types/input_proxy.cpp, tests/data/many-types/input_stub.cpp, tests/data/simple/input_proxy.cpp, tests/data/simple/input_stub.cpp, tests/integration/proxy/testproxymain.cpp
This fixes a bug where properties with signature "ay" had to be null
terminated, which is not always the case.
The issue is that Glib::Variant<std::string>::get() uses
g_variant_get_bytestring() which will return an empty string if the
array does not end with null. It will also only return a part of the
array if the array contains a null character before the end of the
array.
Special handling of signature "ay" is added, so it will use
g_variant_get_fixed_array() instead which works well with any kind of
array payload.
=> Address issue with byte strings that are not null terminated

codegen_glibmm/templates/stub.cpp.templ, codegen_glibmm/templates/stub.h.templ, tests/data/many-types/input_stub.cpp, tests/data/many-types/input_stub.h, tests/data/simple/input_stub.cpp, tests/data/simple/input_stub.h, tests/integration/common/many-types.xml, tests/integration/proxy/testproxymain.cpp, tests/integration/proxy/testproxymain.h, tests/integration/stub/teststubmain.cpp, tests/integration/stub/teststubmain.h
Some architecture needs to multicast  signal for subscriber / publisher model.
but XXX_signal connected emitter basically work on broadcast.
so adding selective signal method work on multicast with uniqueId list gathering from sender invocation data.
=> Add selective signal method to support multicast
